#
# This config.toml is an example and based on the ananke theme
# https://github.com/theNewDynamic/gohugo-theme-ananke/.
#
# If you use a different theme, you might need to change the content of config.toml
# to your liking.
#

#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
theme = ["github.com/thegeeklab/hugo-geekdoc"]

baseurl = "https://s.toplist.cz/about/public/"
title = "O TOPlist.cz"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "cs-CZ"
resourceDir = "../resources"
#relativeURLs = true

DefaultContentLanguage = "cs"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[languages]
  [languages.cs]
    title = "Ananke"
    weight = 1
    contentDir = "content/cs"
  [languages.en]
    title = "Ananke English"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  geekdocLogo = "logo_64.png"
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
