[build]
    publish = "public"
    command = "npm run build"

[build.environment]
    DART_SASS_VERSION = "1.69.7"
    HUGO_VERSION = "0.121.1"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    NODE_VERSION = "18.19.0"
    NPM_VERSION = "10.2.3"

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = """\
            default-src 'self'; \
            child-src 'self'; \
            script-src 'self' \
                'sha256-qRb0NW+En0SpvYuyVZuv+SgwRsZYm13QPAQi/liYDtU='; \
            style-src 'self'; \
            object-src 'none'; \
            base-uri 'self'; \
            connect-src 'self'
                https://*.toplist.cz ; \
            font-src 'self'; \
            frame-src 'self'; \
            img-src 'self' data: https://toplist.cz https://tile.openstreetmap.org; \
            manifest-src 'self'; \
            media-src 'self' \
            """
        X-Frame-Options = "SAMEORIGIN"
        Referrer-Policy = "strict-origin"
        Permissions-Policy = """\
            geolocation=(), \
            midi=(), \
            sync-xhr=(), \
            microphone=(), \
            camera=(), \
            magnetometer=(), \
            gyroscope=(), \
            fullscreen=(), \
            payment=() \
            """
        cache-control = """\
            max-age=0, \
            no-cache, \
            no-store, \
            must-revalidate \
            """
        Access-Control-Allow-Origin = "*"

[context.deploy-preview]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
    command = "npm run build"

[context.next.environment]
    HUGO_ENV = "next"

[dev]
    framework = "#custom"
    command = "npm run start"
    targetPort = 1313
    port = 8888
    publish = "public"
    autoLaunch = false
